name: generate

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configuring
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Generate
        run: |
          chmod +x ./create.sh
          ./create.sh

      - name: Encrypt
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          zip -P "$PASSWORD" config.zip config.json
          rm config.json

      - name: Commit
        run: |
          git add config.zip || true
          if git diff --staged --quiet; then exit 0; fi
          git commit -m "update encrypted config.zip"
          git push origin HEAD
