name: Update

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions[bot]"

      - name: Generate
        run: |
          chmod +x ./create.sh
          ./create.sh

      - name: Commit
        run: |
          git add config.json || true
          if git diff --staged --quiet; then exit 0; fi
          git commit -m "update config.json"
          git push origin HEAD
